refactor: change gutter directives to modern angular
angular-split/angular-split pull request #479
Opened 2024-11-23 14:49 UTC by Harpush

2025-01-05 08:57 UTC, Jefiozie requested changes
I have some small things I think it is easy fixable

2025-01-05 08:57 UTC, Jefiozie commented on projects/angular-split/src/lib/gutter/split-gutter-drag-handle.directive.ts
> +    this.gutterDir._removedFromMap(this.gutterDir._gutterToHandleElementMap, this.gutterNum, this.elementRef)
Would it be possible to use the [DestroyRef](https://angular.dev/api/core/DestroyRef) for this part?

```ts
const destroyRef = [inject](https://angular.dev/api/core/inject)(DestroyRef);
// register a destroy callback
const unregisterFn = destroyRef.onDestroy(() => doSomethingOnDestroy());
```

2025-01-05 08:57 UTC, Jefiozie commented on projects/angular-split/src/lib/gutter/split-gutter-dynamic-injector.directive.ts
> +    })
@SanderElias  what is your opinion on this part? Would there be a better approach to do this?

2025-01-05 08:57 UTC, Jefiozie commented on projects/angular-split/src/lib/gutter/split-gutter-exclude-from-drag.directive.ts
>    }
Would it be possible to use the [DestroyRef](https://angular.dev/api/core/DestroyRef) for this part?

```ts
const destroyRef = [inject](https://angular.dev/api/core/inject)(DestroyRef);
// register a destroy callback
const unregisterFn = destroyRef.onDestroy(() => doSomethingOnDestroy());
```

2025-01-09 19:00 UTC, Harpush commented on projects/angular-split/src/lib/gutter/split-gutter-drag-handle.directive.ts
> +    this.gutterDir._removedFromMap(this.gutterDir._gutterToHandleElementMap, this.gutterNum, this.elementRef)
Well I can use it. What's the benefit vs ngOnDestroy though?

2025-01-09 19:01 UTC, Harpush commented on projects/angular-split/src/lib/gutter/split-gutter-dynamic-injector.directive.ts
> +    })
I will be happy to. Unfortunately as it is a directive I can't use binding in the HTML so I used an effect

2025-01-11 07:00 UTC, Jefiozie commented on projects/angular-split/src/lib/gutter/split-gutter-drag-handle.directive.ts
> +    this.gutterDir._removedFromMap(this.gutterDir._gutterToHandleElementMap, this.gutterNum, this.elementRef)
The behaviour is the same I find the approach a bit cleaner.

2025-01-11 07:03 UTC, Jefiozie commented on projects/angular-split/src/lib/gutter/split-gutter-dynamic-injector.directive.ts
> +    })
Let's leave it for now I can't come up with a better alternative approach

2025-01-11 07:05 UTC, Jefiozie approved these changes

2025-01-11 07:07 UTC, merged